best_args = {
     'random-mnist': {
    'derpp':    {180: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.1,
                        'beta': 0.5,
                        'batch_size': 32},
                 360: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.1,
                        'beta': 0.5,
                        'batch_size': 32},
                 900: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.1,
                        'beta': 0.5,
                        'batch_size': 32},
                 1800: {'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.1,
                        'beta': 0.5,
                        'batch_size': 32},
                 3600: {'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.1,
                        'beta': 0.5,
                        'batch_size': 32},
                },
    'xder':    {180: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.2,
                        'beta': 1.0,
                        'gamma': 0.85,
                        'optim_wd': 0,
                        'optim_mom': 1e-06,
                        'lambd': 0.05,
                        'eta': 0.001,
                        'simclr_temp': 5,
                        'simclr_batch_size': 32,
                        'simclr_num_aug': 2,
                        'batch_size': 32,
                        'm': 0.7},
                360: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.2,
                        'beta': 1.0,
                        'gamma': 0.85,
                        'optim_wd': 0,
                        'optim_mom': 1e-06,
                        'lambd': 0.05,
                        'eta': 0.001,
                        'simclr_temp': 5,
                        'simclr_batch_size': 32,
                        'simclr_num_aug': 2,
                        'batch_size': 32,
                        'm': 0.7},
                900: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.2,
                        'beta': 1.0,
                        'gamma': 0.85,
                        'optim_wd': 0,
                        'optim_mom': 1e-06,
                        'lambd': 0.05,
                        'eta': 0.001,
                        'simclr_temp': 5,
                        'simclr_batch_size': 32,
                        'simclr_num_aug': 2,
                        'batch_size': 32,
                        'm': 0.7},
                1800: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.2,
                        'beta': 1.0,
                        'gamma': 0.85,
                        'optim_wd': 0,
                        'optim_mom': 1e-06,
                        'lambd': 0.05,
                        'eta': 0.001,
                        'simclr_temp': 5,
                        'simclr_batch_size': 32,
                        'simclr_num_aug': 2,
                        'batch_size': 32,
                        'm': 0.7},
                3600: { 'lr': 0.03,
                        'minibatch_size': 32,
                        'alpha': 0.2,
                        'beta': 1.0,
                        'gamma': 0.85,
                        'optim_wd': 0,
                        'optim_mom': 1e-06,
                        'lambd': 0.05,
                        'eta': 0.001,
                        'simclr_temp': 5,
                        'simclr_batch_size': 32,
                        'simclr_num_aug': 2,
                        'batch_size': 32,
                        'm': 0.7},
                }
    }
}